name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
      
    - name: Build
      run: cargo build --release
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: kanto-curses
        path: target/release/kanto-curses

